/* eslint-disable */
/* prettier-ignore-start */
// Auto-generated by pyde-tsgen. Do not edit by hand.
// Source ABI: 29 function(s), 0 event(s).

export interface StorageStressContract {
  allowance(arg0: bigint, arg1: bigint): Promise<bigint>;
  approve(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  balance_of(arg0: bigint): Promise<bigint>;
  clear_balance(arg0: bigint): Promise<void>;
  clear_string(): Promise<void>;
  clear_vec_u64(): Promise<void>;
  deposit(arg0: bigint, arg1: bigint): Promise<void>;
  get_addr(): Promise<string>;
  get_bool(): Promise<boolean>;
  get_bytes(): Promise<Uint8Array>;
  get_bytes32(): Promise<unknown>;
  get_hash(): Promise<unknown>;
  get_i128(): Promise<bigint>;
  get_i32(): Promise<number>;
  get_i8(): Promise<number>;
  get_name(arg0: bigint): Promise<string>;
  get_string(): Promise<string>;
  get_triple(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  get_u128(): Promise<bigint>;
  get_u16(): Promise<number>;
  get_u32(): Promise<number>;
  get_u64(): Promise<bigint>;
  get_u8(): Promise<number>;
  get_vec_addr(): Promise<unknown>;
  get_vec_u64(): Promise<unknown>;
  init(): Promise<void>;
  set_name(arg0: bigint, arg1: string): Promise<void>;
  set_triple(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  transfer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<boolean>;
}

/* prettier-ignore-end */
