/**
 * ABI → TypeScript codegen.
 *
 * Reads an `otigen build` artifact (the `.abi.json` file emitted alongside
 * the `.wasm`) and produces a `.d.ts` ambient module declaring:
 *
 *   1. Strongly typed method signatures (one per contract function)
 *   2. Strongly typed event records (one per declared event)
 *   3. A `<ContractName>Contract` interface that callers can use to
 *      narrow the generic `Contract` from `pyde-ts-sdk`:
 *
 *      ```ts
 *      import { Contract } from "pyde-ts-sdk";
 *      import type { CounterContract } from "./counter.d.ts";
 *
 *      const counter = await Contract.fromArtifact(...) as unknown as CounterContract;
 *      const balance = await counter.balance_of("0xabc...");  // bigint
 *      ```
 *
 * Spec: SDK_AUTHOR_GUIDE + HOST_FN_ABI §3.7 (`pyde.abi` ContractAbi shape).
 */

interface AbiFunction {
  name: string;
  params: { name: string; type: string }[];
  returns: string;
  view: boolean;
  payable: boolean;
}

interface AbiEvent {
  name: string;
  fields: { name: string; type: string; indexed: boolean }[];
}

interface AbiArtifact {
  /** Contract name — used as the prefix for emitted interfaces. */
  name?: string;
  /** Either `{abi: {...}}` or the abi object at root. */
  abi?: {
    functions?: AbiFunction[];
    events?: AbiEvent[];
  };
  functions?: AbiFunction[];
  events?: AbiEvent[];
}

/** Map an ABI scalar type to its TS type. */
function tsType(abiType: string): string {
  const t = abiType.trim();
  switch (t) {
    case "u8":
    case "u16":
    case "u32":
    case "i8":
    case "i16":
    case "i32":
      return "number";
    case "u64":
    case "u128":
    case "u256":
    case "i64":
    case "i128":
    case "i256":
      return "bigint";
    case "bool":
      return "boolean";
    case "String":
    case "string":
      return "string";
    case "Address":
      return "string";
    case "Hash":
    case "hash32":
      return "string";
    case "Bytes":
    case "bytes":
      return "Uint8Array";
    case "()":
    case "unit":
    case "void":
      return "void";
  }
  // Vec<T>
  const vecMatch = /^Vec<(.+)>$/.exec(t);
  if (vecMatch) return `${tsType(vecMatch[1]!)}[]`;
  // Fallback — pass through as unknown so consumers cast explicitly.
  return "unknown";
}

function safeIdent(name: string): string {
  return /^[a-zA-Z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function paramSig(p: { name: string; type: string }): string {
  return `${safeIdent(p.name)}: ${tsType(p.type)}`;
}

function methodSig(fn: AbiFunction): string {
  const args = fn.params.map(paramSig).join(", ");
  const ret = tsType(fn.returns);
  const lines: string[] = [];
  // TSDoc block — pulls flags from the ABI for the reader.
  const flags: string[] = [];
  if (fn.view) flags.push("view");
  if (fn.payable) flags.push("payable");
  if (flags.length > 0) lines.push(`  /** ${flags.join(" · ")} */`);
  lines.push(`  ${safeIdent(fn.name)}(${args}): Promise<${ret === "void" ? "void" : ret}>;`);
  return lines.join("\n");
}

function eventInterface(prefix: string, ev: AbiEvent): string {
  const fields = ev.fields
    .map((f) => `  /** ${f.indexed ? "indexed · " : ""}${f.type} */\n  ${safeIdent(f.name)}: ${tsType(f.type)};`)
    .join("\n");
  return `export interface ${prefix}${ev.name}Event {\n${fields}\n}`;
}

/**
 * Generate a TypeScript declaration file for a Pyde contract ABI.
 *
 * @param abiJson  Raw JSON content of the `*.abi.json` artifact (or the
 *                 ABI object stringified).
 * @param contractName  Optional name used as the prefix for emitted
 *                      interfaces. Falls back to `abi.name` or
 *                      `"Contract"`.
 */
export function generateTypes(abiJson: string, contractName?: string): string {
  const artifact: AbiArtifact = JSON.parse(abiJson);
  const abi = artifact.abi ?? artifact;
  const functions = abi.functions ?? [];
  const events = abi.events ?? [];
  const name = contractName ?? artifact.name ?? "Contract";

  const header = [
    `/* eslint-disable */`,
    `/* prettier-ignore-start */`,
    `// Auto-generated by pyde-tsgen. Do not edit by hand.`,
    `// Source ABI: ${functions.length} function(s), ${events.length} event(s).`,
    ``,
  ].join("\n");

  const methods = functions.map(methodSig).join("\n");
  const contractIface = `export interface ${name}Contract {\n${methods || "  // (no functions in ABI)"}\n}`;

  const eventBlock = events.length > 0
    ? "\n\n" + events.map((ev) => eventInterface(name, ev)).join("\n\n")
    : "";

  return [header, contractIface + eventBlock, ``, `/* prettier-ignore-end */`, ``].join("\n");
}
